name: Setup Elixir
description: Simultaneously setup Elixir, Erlang and cache each build

branding:
  icon: package
  color: blue

inputs:
  otp-version:
    description: Nominate a specific Erlang/OTP version
    required: true
  elixir-version:
    description: Nominate a specific Elixir version
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Elixir and OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.otp-version }}
        elixir-version: ${{ inputs.elixir-version }}

    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache-deps
      with:
        path: deps
        key: ${{ runner.os }}-${{ inputs.elixir-version }}-${{ inputs.otp-version }}-deps-${{ hashFiles('**/mix.lock') }}

    - name: Cache build
      uses: actions/cache@v3
      id: cache-build
      with:
        path: _build
        key: ${{ runner.os }}-${{ inputs.elixir-version }}-${{ inputs.otp-version }}-build-${{ hashFiles('**/mix.lock') }}
